### ISSUE TITLE
Disabled buttons

### ISSUE THREAD

**Issue by peterpahlman** [scania/corporate-ui#233]
To no lose visual impact I think disabled buttons should have the opacity set to 60% instead of 50%. Also I'm not sure if the .disabled-class actually exists? Heard one developer say that it didn't... Great if you can look into this :)

**Comment by mmexvr** [comment]
#234 
#232

**Comment by scania-bootstrap** [comment]
disabled and readonly are not available as CSS classes, rather than HTML attributes. This is the standard way of coding so we style according to that standard (as do Bootstrap):

HTML
<button type="button" class="btn btn-primary" disabled="true">Primary</button>

CSS (should remain in Corporate UI)
.btn-primary:disabled, .btn-primary.disabled,
.btn-primary[disabled] {
....
}

Samples of other HTML attributes are: alt, autocomplete, autofocus.

![image](https://user-images.githubusercontent.com/10209902/45882017-299dcf00-bdad-11e8-9073-1acd4b258ffd.png)

**Comment by scania-bootstrap** [comment]
@peterpahlman the other day I was attending a presentation where a presenter tried to click a disabled primary button about 25 times (at different stages of the demo). It must be very clear what's disabled or not from a UX perspective. Opacity doesn't hold.

**Comment by scania-bootstrap** [comment]
Can you please sketch on a new disabled button togheter with Parag?

**Comment by scania-bootstrap** [comment]
https://scania.github.io/corporate-ui-docs/developer/bootstrap-original-docs.html#buttons

You'll find the disabled state there.

**Comment by mmexvr** [comment]
Simple solution: change to gray

**Comment by helloimela** [comment]
We will not add new feature in corporate-ui 3. New button UI is being designed now. Will take this issue into consideration. Please use new design button in corporate-ui 4.

**Comment by helloimela** [comment]
Issue will be closed due to inactivity. Final design for buttons will be implemented in version 4.
