### ISSUE TITLE
Table-panel offset background-color

### ISSUE THREAD

**Issue by fomekh** [scania/corporate-ui#277]
**Describe the bug**
Table-panel offset background-color

**To Reproduce**
1. Go to '/driver-evaluation/driver-data'

**Expected behavior**
The background color should be applied inside the table

**Screenshots**
![table-panel offset background color desktop](https://user-images.githubusercontent.com/6946108/46475939-2c55e680-c7e7-11e8-9977-c5579d0fcad1.PNG)

![table-panel offset background color mobile](https://user-images.githubusercontent.com/6946108/46475943-2eb84080-c7e7-11e8-9b1e-6ea2266ab406.PNG)

**Comment by scania-bootstrap** [comment]
.table-panel is not the issue here rather than it is applied to the DIV that surrounds the table (pictured below). The .table-panel class should be moved so it is applied to the table itself. Like this:

 class="table table-panel table-striped table-hover table-selectable"

:-)

Will you fix? You might want to search for table-panel through the whole site to verify it's not present at the wrong places elsewhere.

WRONG;
![image](https://user-images.githubusercontent.com/10209902/46479832-447e3380-c7f0-11e8-86fb-e6d305af3b99.png)

**Comment by scania-bootstrap** [comment]
Can you close the issue when you've read the explaination?
