### ISSUE TITLE
Tooltips not working with bs4 class

### ISSUE THREAD

**Issue by romainSaya** [scania/corporate-ui#483]
**Version of Corporate-ui**<br/>
3.5.3-1

**Describe the bug**<br/>
Tooltips are not working when adding `bs4` class to the body section.

**To Reproduce**<br/>
Use this
```
<body class="scania app bs4" id="app-root">
    <a href="https://google.com" title="Google" data-toggle="tooltip">Google</a>
</body>
```
then the tooltip is not working.
When you remove the bs4 class, tooltips are working again

**Expected behavior**<br/>
It's excepted to be working with bootstrap 4 classes

**Desktop (please complete the following information):**<br/>
 - OS: Windows 10
 - Browser Chrome 
 - Version 78

**Smartphone (please complete the following information):**<br/>
 - No

**Comment by helloimela** [comment]
Hello, thank you for reporting the issue.
If you want to use bootstrap4, we suggest you to implement corporate-ui version 4.
In the near future, we will drop support for corporate-ui 3 and we decided not to add more features or implement fixes that is fixed in corporate-ui 4. So, please try our new version, and if problem appears please report a new issue!
Thank you!

**Comment by helloimela** [comment]
Check out our latest docs here : https://digitaldesign.scania.com/components/
And how to use bootstrap with CUI : https://digitaldesign.scania.com/faqs/faq-development

**Comment by helloimela** [comment]
Hello @romainSaya is there any breaking issue with this ? If not, we will close this issue since we are not going to add new feature in Corporate UI 3. For more information please read announcement in Teams channel: [link](https://teams.microsoft.com/l/message/19:7a4c1fa7280f4fcdbda85a6758b22b01@thread.skype/1598345607959?tenantId=3bc062e4-ac9d-4c17-b4dd-3aad637ff1ac&groupId=79f9bfeb-73e2-424d-9477-b236191ece5e&parentMessageId=1598345607959&teamName=Scania%20Digital%20Design%20System&channelName=Announcements&createdTime=1598345607959)
