### ISSUE TITLE
@font-face error in IE

### ISSUE THREAD

**Issue by mmexvr** [scania/corporate-ui#51]
**Describe the bug**

@font-face error appears in IE
CSS3111: @font-face encountered unknown error.
ScaniaSans-Regular.eot
CSS3111: @font-face encountered unknown error.
ScaniaSansHeadline-Regular.eot
CSS3111: @font-face encountered unknown error.
ScaniaSansHeadline-Bold.eot

**To Reproduce**
1. Go to localhost:1337
2. Look at the console

**Screenshots**
![font-face-error-ie](https://user-images.githubusercontent.com/35451568/41601280-54a059e4-73d8-11e8-888d-43281929ad39.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 67

**Comment by scania-bootstrap** [comment]
This is due to a error in the font face file itself, as delivered by Brand Union. It does not affect the User Experience or has any technical implications. It is just an error message that do mean nothing and we should not currently spend time on it.

**Comment by scania-bootstrap** [comment]
You'll find the same "issue" on Scania.Com.

**Comment by scania-bootstrap** [comment]
"CSS3111 is usually caused by an issue with the font's binary source. One of the popular online TTF to EOT converters for example produces EOT files with a NAME table that doesn't comply to the Microsoft standards, which results in EOT fonts that never load in IE and produce the CSS3111 error. So, when you experience a CSS3111, it is always good to try using a different TTF to EOT converter or font face generator."

The problem is that Brand Union are hosting the font master files and they are not very competent on web fonts.
