### ISSUE TITLE
Bug - Modal graybackground stays on DOM

### ISSUE THREAD

**Issue by gabrielgirodo** [scania/corporate-ui#537]
**Describe the bug**  
Modal gray background remains on the application when we press the browser's back button

**To Reproduce**   
_Steps to reproduce the behavior:_  
Once the user triggers a popup we see the modal and its gray background which prevents the user from clicking on the other stuff outside the modal. However if the user clicks on the browser's back arrow the application navigates to the previous page but the gray background is kept on the page.

**Expected behavior**  
Modal gray background be gone when navigating through pages

**Version of Corporate-ui**  
3.5.3

**Framework and version**  
_If you use any specific framework please provide information_
- Framework: Angular
- Version: 6

**Application link**  
_Provide link if possible_  
- https://web.pii-dev.devtest.aws.scania.com/

**Desktop information:**  
_Please complete the following information_
 - Browser chrome
 - Version 79
 - OS: Windows 10

**Comment by mmexvr** [comment]
Hello, nice that you reported it! :) 

Can you please follow the structure of creating a issue.

https://github.com/scania/corporate-ui/issues/new?assignees=&labels=bug&template=bug_report.md&title=Bug+-+%22title+text%22

**Comment by helloimela** [comment]
This issue apparently appeared when using bootstrap modal in SPA both in corporate-ui 3 and 4.
The fixes can be done from corporate-ui side or project side.
From project side, it could be like this: everytime navigation occurred, hide bootstrap modal backdrop
`$('.modal-backdrop').remove();`

Do you think it should be implemented as a solution from corporate-ui?
It can be tricky from corporate-ui script, because we need to access the DOM and it could be different from one project to another.
One possible solution is to add it to c-modal component.

Interesting discussion: https://stackoverflow.com/questions/11519660/twitter-bootstrap-modal-backdrop-doesnt-disappear

Please give us update if you have found a solution so far @gabrielgirodo ! Thanks! :)

**Comment by helloimela** [comment]
A month ago we announced about deprecation of Corporate UI 3 in 1 year, we will only provide support for severe bugs. We will close this issue for now. Please check solution in Corporate UI 4 and if the problem appears, we will solve it in version 4.

**Comment by helloimela** [comment]
Link to announcement in Teams: [link](https://teams.microsoft.com/l/message/19:7a4c1fa7280f4fcdbda85a6758b22b01@thread.skype/1598345607959?tenantId=3bc062e4-ac9d-4c17-b4dd-3aad637ff1ac&groupId=79f9bfeb-73e2-424d-9477-b236191ece5e&parentMessageId=1598345607959&teamName=Scania%20Digital%20Design%20System&channelName=Announcements&createdTime=1598345607959)
